version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    cooldown:
      default-days: 1
    open-pull-requests-limit: 20
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'daily'
    cooldown:
      default-days: 1
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    cooldown:
      default-days: 1
